---
- name: Obtain Let's Encrypt certificate
  community.general.acme_certificate:
    domains:
      - "{{ bitwarden_hostname }}"
    cert_file: "/tmp/bwdata/ssl/{{ bitwarden_hostname }}/fullchain.pem"
    key_file: "/tmp/bwdata/ssl/{{ bitwarden_hostname }}/privkey.pem"
    challenge: http-01
    contact_email: "{{ emailAddr }}" # Replace with your email address
    agreement_url: https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
  register: acme_cert_result
  ignore_errors: true  # Ignore errors in case the certificate is already obtained

- name: Convert certificate and private key to PFX
  openssl_pkcs12:
    action: export
    path: "/tmp/bwdata/ssl/identity.pfx"
    name: "{{ bitwarden_hostname }}"  # Replace with your domain
    privatekey_path: "/tmp/bwdata/ssl/{{ bitwarden_hostname }}/privkey.pem"
    certificate_path: "/tmp/bwdata/ssl/{{ bitwarden_hostname }}/fullchain.pem"
    passphrase: "{{ certificate_password }}"  # Set your desired passphrase here
  when: acme_cert_result is succeeded

# - name: Clean up Let's Encrypt certificate files
#   file:
#     path: /etc/letsencrypt/live/yourdomain.com
#     state: absent
#   when: acme_cert_result is succeeded
