---
# tasks file for letsencrypt_certificate

- name: Ensure certbot is installed
  ansible.builtin.package:
    name: certbot
    state: present

- name: Request Let's Encrypt certificate using standalone method
  command: "certbot certonly --standalone --preferred-challenges http -d {{ bitwarden_hostname }} -m {{ emailAddr }} --cert-name {{ bitwarden_hostname }} --agree-tos -n"
  register: certbot_output

- name: Copy certificates to Bitwarden directory
  copy:
    src: "/etc/letsencrypt/live/{{ bitwarden_hostname }}/"
    dest: "{{ install_location_prefix }}/ssl/{{ bitwarden_hostname }}/"
    mode: '0500'

- name: Whoami
  command: whoami
  register: currentuser

- name: Usernamu running
  debug:
    msg: "{{ currentuser.stdout }}"

- name: Create pfx file and copy to bitwarden location
  command: "openssl pkcs12 -export -out {{ install_location_prefix }}/identity/identity.pfx -inkey {{ install_location_prefix }}/ssl/{{ bitwarden_hostname }}/privkey.pem -in {{ install_location_prefix }}/ssl/{{ bitwarden_hostname }}/cert.pem -passout pass:{{ certificate_password }}"

# - name: Extract certificate and private key paths
#   set_fact:
#     certificate_path: "{{ certbot_output.stdout_lines | regex_search('Certificate is saved at: (.*)', '\\1') }}"
#     private_key_path: "{{ certbot_output.stdout_lines | regex_search('Key is saved at: (.*)', '\\1') }}"

# - name: Let's Encrypt output
#   debug:
#     msg: "Cert location: {{ certificate_path }} | Private key location: {{ private_key_path }}"