---
- name: Include the variable file
  ansible.builtin.include_vars:
    file: vars/vars.yml

- name: Verify vars are assigned
  assert:
    that: "{{ item }} is defined"
  loop: "{{ required_vars }}"
  loop_control:
    loop_var: item

- name: Prepare environment
  include_tasks: tasks/preTasks.yml

- name: Install Bitwarden
  include_tasks: tasks/installBitwarden.yml