- name: Create docker group
  group:
    name: docker
    state: present

- name: Create Bitwarden user
  user:
    name: bitwarden
    uid: 1001
    groups: docker
    password: Password123
    append: yes

- name: Create Bitwarden directory
  file:
    path: /opt/bitwarden
    state: directory
    mode: 700
    owner: bitwarden
    group: bitwarden

- name: Create docker-stub-EU tmp directory
  file:
    path: /tmp/docker-stub-EU
    state: directory
    mode: 777
    owner: bitwarden
    group: bitwarden